---
namespace: adfinis
name: proxmox_upgrade
version: 0.1.0
readme: README.md
authors:
  - Adfinis <support@adfinis.com>
description: An ansible collection for automated proxmox cluster upgrades
license_file: 'LICENSE'
tags:
  - linux
  - proxmox
  - upgrade
dependencies:
  community.general: ">=9.5.1"
repository: https://github.com/adfinis/ansible-collection-proxmox_upgrade
documentation: https://github.com/adfinis/ansible-collection-proxmox_upgrade
homepage: https://adfinis.com/
issues: http://github.com/adfinis/ansible-collection-proxmox_upgrade/issues
build_ignore: []
