---
- name: Run prechecks for cluster upgrade
  hosts: pve_nodes
  gather_facts: false
  become: true
  roles:
    - role: adfinis.proxmox_upgrade.precheck

- name: Upgrade full proxmox cluster
  hosts: pve_nodes
  gather_facts: false
  serial: 1
  become: true
  roles:
    - role: adfinis.proxmox_upgrade.proxmox_upgrade
      vars:
        proxmox_upgrade_confirm_migration: false

- name: Distribute VMs on all nodes
  hosts: pve_nodes
  gather_facts: false
  run_once: true
  become: true
  roles:
    - role: adfinis.proxmox_upgrade.proxmox_load_balance
      vars:
        proxmox_load_balance_confirm_migration: false
