---
name: Build and deploy Collection on Ansible Galaxy
on:
  release:
    types:
      - published

permissions: {}

jobs:
  deploy:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-collection.yaml@e64e43cab282caa112c5fa5df4d43fd82ed8711f # v0.9.0
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
