---
name: Build and deploy Collection on Ansible Galaxy
on:
  release:
    types:
      - published

permissions: {}

jobs:
  deploy:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-collection.yaml@7b2184d76870cc7c281d081a6ebabc15264dcc1f # v0.10.0
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
