---
name: Build and deploy Collection on Ansible Galaxy
on:
  release:
    types:
      - published

jobs:
  deploy:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-collection.yaml@v0.5.2
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
