---
name: Build and deploy Collection on Ansible Galaxy
on:
  release:
    types:
      - published

permissions: {}

jobs:
  deploy:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-collection.yaml@87808cf15c59f09c5e6e3b8eefedc373e4b29680 # v0.5.2
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
