---
# runs on each push to main and is responsible for creating new tags/releases
name: Create Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  semantic-release:
    uses: adfinis/github-workflows-bareos/.github/workflows/semantic-release.yaml@e64e43cab282caa112c5fa5df4d43fd82ed8711f # v0.9.0
    secrets:
      ADFINISBOT_GITHUB_TOKEN: ${{ secrets.ADFINISBOT_GITHUB_TOKEN }}
