---
# runs on each push to main and is responsible for creating new tags/releases
name: Create Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  semantic-release:
    uses: adfinis/github-workflows-bareos/.github/workflows/semantic-release.yaml@7b2184d76870cc7c281d081a6ebabc15264dcc1f # v0.10.0
    secrets:
      ADFINISBOT_GITHUB_TOKEN: ${{ secrets.ADFINISBOT_GITHUB_TOKEN }}
